### ISSUE TITLE
Actividad 10.

### ISSUE THREAD

**Issue by A-Lorely-Z** [SistemasTecTlaxiaco/actividad-10-expresiones-boolenas-lennin-s-team-1as#1]
[MD PRACTICA 7 UNIDAD 4 (1).pdf](https://github.com/user-attachments/files/18044435/MD.PRACTICA.7.UNIDAD.4.1.pdf)

**Comment by AlynGomez12** [comment]
Portada:25/25
Procedimiento/Desarrollo:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
